### ISSUE TITLE
Better error for not providing a version

### ISSUE THREAD

**Issue by mj-cycls** [Cycls/SaryaSDK#4]
I get this error when I run the hello world example since I haven't provided a version to the client

```
Traceback (most recent call last):
  File "/home/runner/another-one/main.py", line 3, in <module>
    sarya = SaryaClient(name="another",description="hello world marid",
  File "/home/runner/another-one/.pythonlibs/lib/python3.10/site-packages/sarya/client.py", line 56, in __init__
    self._set_app()
  File "/home/runner/another-one/.pythonlibs/lib/python3.10/site-packages/sarya/client.py", line 78, in _set_app
    self.app = FastAPI(title=self.name, description=self.description, version=self.version)
  File "/home/runner/another-one/.pythonlibs/lib/python3.10/site-packages/fastapi/applications.py", line 879, in __init__
    assert self.version, "A version must be provided for OpenAPI, e.g.: '2.1.0'"
AssertionError: A version must be provided for OpenAPI, e.g.: '2.1.0'
```

Perhaps a version for the `app/marid` is not really needed at the moment.

**Comment by kk-cycls** [comment]
it should not matter, the version should be an optional 
will solve it

**Comment by kk-cycls** [comment]
Now, you can provide the version of your Marid or not
